name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

concurrency:
  group: 'production'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: Delete zero byte files
        run: find ./dist -size 0c -delete
      - uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ vars.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftps
          local-dir: ./dist/
          server-dir: ${{ vars.REMOTE_DIR }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
